name: entitlements-expiration-job
namespace: astro-staging
image:
  group: ghcr.io/bot-astro
  name: entitlements-expiration-job
  tag: latest
config: entitlements-expiration-job-config
resources:
  requests:
    cpu: 50m
    memory: 250Mi