name: entitlements-expiration-job
namespace: astro
image:
  group: ghcr.io/your-org
  name: entitlements-expiration-job
  tag: latest
config: entitlements-expiration-job-config
resources:
  requests:
    cpu: 50m
    memory: 250Mi