info:
  app:
    name: "Bot"
    description: "The bot Discord application."
    version: "1.0.0"

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: GET, POST
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

logging:
  level:
    root: ${LOG_LEVEL:INFO}
