info:
  app:
    name: "Bot"
    description: "The main bot Discord application."
    version: "1.0.0"

server:
  port: 9000

management:
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: GET, POST
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      group:
        readiness:
          include:
            - readinessState
        liveness:
          include:
            - livenessState
  prometheus:
    metrics:
      export:
        enabled: true

##############
### SHARED ###
##############
logging:
  level:
    root: ${LOG_LEVEL:INFO}


sentry:
  dsn: https://16d5963ef1bc772e7881083afe2807d8@o4506708022263808.ingest.sentry.io/4506708023967744
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 0.05