info:
  app:
    name: "Bot"
    description: "The main bot Discord application."
    version: "1.0.0"

management:
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: GET, POST
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  prometheus:
    metrics:
      export:
        enabled: true

application:
  features:
    premium-restrictions: ${PREMIUM_RESTRICTIONS:false}

discord:
  application:
    token: ${BOT_TOKEN}
    bot-id: ${BOT_ID:788708323867885568}
    command-guilds: [1026552055046881402]

##############
### SHARED ###
##############
logging:
  level:
    root: ${LOG_LEVEL:INFO}


sentry:
  dsn: https://16d5963ef1bc772e7881083afe2807d8@o4506708022263808.ingest.sentry.io/4506708023967744
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 0.7

bigquery:
  enabled: ${BIGQUERY_ENABLED:false}
  dataset-name: ${BIGQUERY_DATASET_NAME:astro_local}

chargebee:
  api-key: ${CHARGEBEE_API_KEY}
  webhook-token: ${CHARGEBEE_WEBHOOK_TOKEN}
  site-name: ${CHARGEBEE_SITE_NAME}
kube:
  lifecycle-authorization: ${KUBE_LIFECYCLE_AUTHORIZATION}
support:
  bot:
    base-url: ${SUPPORT_BOT_BASE_URL:http://localhost:9001}
    origin-url: ${SUPPORT_BOT_ORIGIN_URL:http://localhost:3000}
    auth: ${SUPPORT_BOT_AUTH:dev-premium-api-auth-token}

io:
  influx:
    bucket: ${INFLUX_BUCKET:astro-logs}
    org: ${INFLUX_ORG:astro-org}
    token: ${INFLUX_TOKEN:astroverysecuretoken}
    url: ${INFLUX_URL:http://localhost:8086}
  mongo:
    connection-string: ${MONGO_CONNECTION_STRING:mongodb://localhost:27017}
    database: ${MONGO_DATABASE:AstroDev}
  redis:
    uris: ${REDIS_URIS:redis://localhost:6379}
    cluster: ${REDIS_CLUSTER:false}

#####################
### END OF SHARED ###
#####################

shard:
  manager:
    total-pods: ${SHARD_MANAGER_TOTAL_PODS:1}
    total-shards: ${SHARD_MANAGER_TOTAL_SHARDS:1}