name: support-bot
namespace: astro
image:
  group: ghcr.io/your-org
  name: support-bot
  tag: latest
config: support-bot-config
replicas: 2
auth: Fill with same value as you used for KUBE_LIFECYCLE_AUTHORIZATION in .env files
port: 9002
resources:
  requests:
    cpu: 100m
    memory: 500Mi