info:
  app:
    name: "Support bot with an API"
    description: "A Discord bot that handles the support server of Astro, includes an API for reacting to various events, mainly premium."
    version: "1.0.0"

server:
  port: 9002


management:
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: GET, POST
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      group:
        readiness:
          include:
            - readinessState
        liveness:
          include:
            - livenessState
  prometheus:
    metrics:
      export:
        enabled: true


##############
### SHARED ###
##############
logging:
  level:
    root: ${LOG_LEVEL:INFO}


sentry:
  dsn: https://fd05f462a5f47e39c3cd927fc63a3021@o4506708022263808.ingest.sentry.io/4506708030128128
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 0.05