info:
  app:
    name: "Support bot with an API"
    description: "A Discord bot that handles the support server of Astro, includes an API for reacting to various events, mainly premium."
    version: "1.0.0"

server:
  port: "${PORT:9001}"

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: GET, POST
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      group:
        readiness:
          include:
            - readinessState
        liveness:
          include:
            - livenessState


##############
### SHARED ###
##############
logging:
  level:
    root: ${LOG_LEVEL:INFO}


sentry:
  dsn: https://3d0b9348d1c4d44884fa2cfd45ad1c4e@o4506570641702912.ingest.sentry.io/4506575870230528
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0

bigquery:
  enabled: ${BIGQUERY_ENABLED:false}
  dataset-name: ${BIGQUERY_DATASET_NAME:astro_local}

chargebee:
  api-key: ${CHARGEBEE_API_KEY}
  webhook-token: ${CHARGEBEE_WEBHOOK_TOKEN}
  site-name: ${CHARGEBEE_SITE_NAME}
kube:
  lifecycle-authorization: ${KUBE_LIFECYCLE_AUTHORIZATION}
support:
  bot:
    base-url: ${SUPPORT_BOT_BASE_URL:http://localhost:9001}
    origin-url: ${SUPPORT_BOT_ORIGIN_URL:http://localhost:3000}
    auth: ${SUPPORT_BOT_AUTH:dev-premium-api-auth-token}

io:
  influx:
    bucket: ${INFLUX_BUCKET:astro-logs}
    org: ${INFLUX_ORG:astro-org}
    token: ${INFLUX_TOKEN:astroverysecuretoken}
    url: ${INFLUX_URL:http://localhost:8086}
  mongo:
    connection-string: ${MONGO_CONNECTION_STRING:mongodb://localhost:27017}
    database: ${MONGO_DATABASE:AstroDev}
#  redis:
#    cluster: ${REDIS_CLUSTER:false}
#    host: ${REDIS_HOST:localhost}
#    port: ${REDIS_PORT:6379}
#    password: ${REDIS_PASSWORD:}
#    database: ${REDIS_DATABASE:0}

#####################
### END OF SHARED ###
#####################

discord:
  application:
    bot-id: ${DISCORD_APPLICATION_ID:1176957574332026940}
    token: ${DISCORD_APPLICATION_TOKEN}
    command-guilds: [700607091391594567]
    whitelisted-guilds: [700607091391594567]
    entitlements-bot-id: ${ENTITLEMENTS_BOT_ID:715621848489918495}
    entitlements-bot-token: ${ENTITLEMENTS_BOT_TOKEN}
    guild-id-for-premium-role: ${GUILD_ID_FOR_PREMIUM_ROLE:700607091391594567}
    premium-sku-id: ${PREMIUM_SKU_ID:1096107722115661934}
    premium-role-id: ${PREMIUM_ROLE_ID:761283474241093682}