info:
  app:
    name: "Support bot with an API"
    description: "A Discord bot that handles the support server of Astro, includes an API for reacting to various events, mainly premium."
    version: "1.0.0"

server:
  port: "${PORT:9000}"

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: GET, POST
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      group:
        readiness:
          include:
            - readinessState
        liveness:
          include:
            - livenessState

logging:
  level:
    root: ${LOG_LEVEL:INFO}

sentry:
  dsn: https://fd089382ff78ec76d05f0383289c6ec1@o4506570641702912.ingest.sentry.io/4506570643144704
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0