apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      nodeSelector:
        node.kubernetes.io/agent: "astro"
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.group }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.config }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.port }}
              httpHeaders:
                - name: Authorization
                  value: {{ .Values.auth }}
            initialDelaySeconds: 1
            periodSeconds: 5
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.port }}
              httpHeaders:
                - name: Authorization
                  value: {{ .Values.auth }}
            initialDelaySeconds: 1
            periodSeconds: 5
            failureThreshold: 10
          lifecycle:
            preStop:
              httpGet:
                path: /shutdown
                port: {{ .Values.port }}
                httpHeaders:
                  - name: Authorization
                    value: {{ .Values.auth }}
      imagePullSecrets:
        - name: docker-registry
