apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ing
  namespace: {{ .Values.namespace }}
spec:
  tls:
    - hosts:
        - api.astro-bot.space
      secretName: tls
  rules:
    - host: api.astro-bot.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: central-api
                port:
                  number: 9001