info:
  app:
    name: "Central API"
    description: "A fast and reliable Central API application to manage data for the web."
    version: "1.0.0"

server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      group:
        readiness:
          include:
            - readinessState
        liveness:
          include:
            - livenessState
  prometheus:
    metrics:
      export:
        enabled: true

##############
### SHARED ###
##############
logging:
  level:
    root: ${LOG_LEVEL:INFO}


sentry:
  dsn: https://57acc0d723f47fa990648188825a43bb@o4506708022263808.ingest.sentry.io/4506708031963136
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 0.05