info:
  app:
    name: "Central API"
    description: "A fast and reliable Central API application to mange data for the web."
    version: "1.0.0"

server:
  port: "${PORT:9000}"

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: GET, POST
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      group:
        readiness:
          includes:
            - readinessState
        liveness:
          includes:
            - livenessState

logging:
  level:
    root: ${LOG_LEVEL:INFO}
