info:
  app:
    name: "Central API"
    description: "A fast and reliable Central API application to manage data for the web."
    version: "1.0.0"

server:
  port: ${PORT:9001}

management:
  endpoints:
    web:
      cors:
        allowed-origins: "http://localhost:3000", "https://astro-bot.space"
        allowed-methods: GET, POST, PUT, DELETE
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      group:
        readiness:
          include:
            - readinessState
        liveness:
          include:
            - livenessState
  prometheus:
    metrics:
      export:
        enabled: true

##############
### SHARED ###
##############
logging:
  level:
    root: ${LOG_LEVEL:INFO}


sentry:
  dsn: https://57acc0d723f47fa990648188825a43bb@o4506708022263808.ingest.sentry.io/4506708031963136
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 0.25

bigquery:
  enabled: ${BIGQUERY_ENABLED:false}
  dataset-name: ${BIGQUERY_DATASET_NAME:astro_local}

chargebee:
  api-key: ${CHARGEBEE_API_KEY}
  webhook-token: ${CHARGEBEE_WEBHOOK_TOKEN}
  site-name: ${CHARGEBEE_SITE_NAME}
kube:
  lifecycle-authorization: ${KUBE_LIFECYCLE_AUTHORIZATION}
support:
  bot:
    base-url: ${SUPPORT_BOT_BASE_URL:http://localhost:9001}
    origin-url: ${SUPPORT_BOT_ORIGIN_URL:http://localhost:3000}
    auth: ${SUPPORT_BOT_AUTH:dev-premium-api-auth-token}

io:
  influx:
    bucket: ${INFLUX_BUCKET:astro-logs}
    org: ${INFLUX_ORG:astro-org}
    token: ${INFLUX_TOKEN:astroverysecuretoken}
    url: ${INFLUX_URL:http://localhost:8086}
  kmongo:
    connection-string: ${KMONGO_CONNECTION_STRING:mongodb://localhost:27017}
    database: ${KMONGO_DATABASE:AstroDev}
  redis:
    uris: ${REDIS_URIS:redis://localhost:6379}
    cluster: ${REDIS_CLUSTER:false}


#####################
### END OF SHARED ###
#####################

central:
  api:
    auth: ${CENTRAL_API_AUTH:iqwoenfuef3289fnv3adj0sajda13nd130d9jasdcb123e1pef3289vn}

discord:
  application:
    redirect-uri: ${DISCORD_APPLICATION_REDIRECT_URI:http://localhost:3000/callback}
    id: ${DISCORD_APPLICATION_ID:788708323867885568}
    secret: ${DISCORD_APPLICATION_SECRET}

jwt:
  key: ${JWT_KEY}
bot:
  endpoint:
    localhost: ${BOT_ENDPOINT_LOCALHOST:true}
    port: ${BOT_ENDPOINT_PORT:9000}
    pod-name: ${BOT_ENDPOINT_POD_NAME:astro}
    service-name: ${BOT_ENDPOINT_SERVICE_NAME:bot}
    namespace: ${BOT_ENDPOINT_NAMESPACE:astro}