version: "3.8"
name: "astro-staging-env"

services:
  redis:
    image: redis:latest
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: on-failure
    command: redis-server --save 20 1 --loglevel warning --requirepass t9ffYdGJ9puTOpeEdhEg1LQBBAwB5YpJVjYnZJtp6HpqgtqrE1dGOF7n3gPyXtS2gTTlzwGTKLS6
    volumes:
      - redis:/data
    ports:
      - "6380:6379"
volumes:
  redis: