version: "3.8"
name: "astro-staging-env"

services:
  redis:
    image: redis:latest
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: on-failure
    command: redis-server --save 20 1 --loglevel warning --requirepass t9ffYdGJ9puTOpeEdhEg1LQBBAwB5YpJVjYnZJtp6HpqgtqrE1dGOF7n3gPyXtS2gTTlzwGTKLS6
    volumes:
      - redis:/data
    ports:
      - "6380:6379"
  influx:
    image: influxdb:latest
    container_name: ${COMPOSE_PROJECT_NAME}_influx
    restart: no
    ports:
      - "8087:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: astrouser
      DOCKER_INFLUXDB_INIT_PASSWORD: astropassword
      DOCKER_INFLUXDB_INIT_ORG: astro-org
      DOCKER_INFLUXDB_INIT_BUCKET: astro-logs
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: SQMmOqEg2tphDVhDeC36IuqaSVFGU3
volumes:
  redis: